const fs = require('fs');
const path = require('path');

// Configuration
const TOKEN_PATH = path.join(__dirname, '../tokens/colors.json');
const ANDROID_COLOR_PATH = path.join(__dirname, '../Android/app/src/main/java/com/oatrice/jarwise/ui/theme/Color.kt');
const WEB_THEME_PATH = path.join(__dirname, '../Web/tailwind.theme.js');

// Read Tokens
const tokens = JSON.parse(fs.readFileSync(TOKEN_PATH, 'utf8'));

// ---------------------------------------------------------
// 1. Generate Android Color.kt
// ---------------------------------------------------------
function generateAndroidColors(tokens) {
    let kotlinContent = `package com.oatrice.jarwise.ui.theme

import androidx.compose.ui.graphics.Color

// This file is AUTO-GENERATED by scripts/sync_tokens.js
// Do not edit directly. Edit tokens/colors.json instead.

`;

    for (const [colorName, shades] of Object.entries(tokens)) {
        const capitalizedColor = colorName.charAt(0).toUpperCase() + colorName.slice(1);
        for (const [shade, hex] of Object.entries(shades)) {
            const hexCode = hex.replace('#', '0xFF');
            kotlinContent += `val ${capitalizedColor}${shade} = Color(${hexCode})\n`;
        }
    }

    // Add Gradients manually for now or define a structure for them later
    kotlinContent += `
// Gradients
val GradientBlueToCyan = listOf(Blue500, Cyan400)
`;

    return kotlinContent;
}

const androidContent = generateAndroidColors(tokens);
fs.writeFileSync(ANDROID_COLOR_PATH, androidContent);
console.log(`✅ Android colors generated at: ${ANDROID_COLOR_PATH}`);

// ---------------------------------------------------------
// 2. Generate Web Tailwind Theme Helper
// ---------------------------------------------------------
function generateWebTheme(tokens) {
    const jsContent = `// This file is AUTO-GENERATED by scripts/sync_tokens.js
// Do not edit directly. Edit tokens/colors.json instead.

module.exports = ${JSON.stringify(tokens, null, 2)};
`;
    return jsContent;
}

const webContent = generateWebTheme(tokens);
fs.writeFileSync(WEB_THEME_PATH, webContent);
console.log(`✅ Web theme generated at: ${WEB_THEME_PATH}`);
